### ISSUE TITLE
Ajuste no Config

### ISSUE THREAD

**Issue by agawebdesign** [aleguarita/Front-Alego#22]
Adicionar form-grupo no array $uso-classes dentro do arquivo +config.scss.

$uso-classes: (
  form-field,
*\*  form-grupo,**
  // form-pre,
  form,
  botao,
  botao-secundario,
  autocomplete,
  grid-container,
  tabela,
  tabela-form,
  modal,
  card,
  lista,
  paginacao,
  breadcrumb,
  toaster,
  secao-lista,
);

**Comment by aleguarita** [comment]
pior que já estava
