### ISSUE TITLE
classe field-1 dentro do grid sobrepõe campo anterior

### ISSUE THREAD

**Issue by andrebarca** [aleguarita/Front-Alego#44]
ao usar a classe "field-1" em um checkbox, na mesma linha contendo outros campos do tipo texto, o campo contendo aquela classe fica sobreposto ao campo anterior.

**Comment by agawebdesign** [comment]
Solução:

```

$i: 0;
$max: 12;
$medida: 100% / $max;
@while $i < $max {
    $i: $i + 1;
    .field-#{$i} {
        width: $medida * $i;
        margin: 0;
        padding: .2em;
    }
}
```

A variável $i estava anteriormente setada com valor 1 logo no incremento do loop era pulada a criação da class field-1. Observou-se também que a lógica no while @while $i <= $max permitia a criação da classe field-13, resultado que não era objetivo. Daí retirou-se o sinal de igual para possibilitar a criação somente até a classe field-12.

**Comment by aleguarita** [comment]
A versão de vocês estava desatualizada. Não estava mais usando @while e sim @for. Favor conferir

**Comment by aleguarita** [comment]
Outro problema detectado: quando usava telas menores empurrava. Isso acontecia pelo tamanho máximo da caixa. Resolvido.
